// =============================================================
// BIG STAR MACHINERY - INVENTORY FILE
// This is the ONLY file you normally need to edit.
// To add a machine: copy one item block, paste it at the bottom,
// then change the words, price, category and picture file name.
// =============================================================

const INVENTORY = [
  {
    id: '8511',
    title: '2026 Raytree RMBD72ST 72" Hydraulic Drum Mulcher',
    category: 'Full-Size Skid Steer Attachments',
    type: 'Drum Mulcher',
    price: 8125,
    status: 'Available',
    image: 'assets/images/inventory/raytree-rmbd72st.jpg',
    serial: 'DRM202606202771',
    details: ['Brand new / unused', '72 inch drum mulcher', 'Skid steer attachment', 'Hydraulic drive', 'Delivery available'],
    lot: '8511'
  },
  {
    id: '8512',
    title: '2026 Raytree RMBD72ST 72" Drum Mulcher',
    category: 'Full-Size Skid Steer Attachments',
    type: 'Drum Mulcher',
    price: 8125,
    status: 'Available',
    image: 'assets/images/inventory/raytree-rmbd72st.jpg',
    serial: 'DRM202606202770',
    details: ['Brand new / unused', '72 inch drum mulcher', 'Skid steer attachment', 'Delivery available'],
    lot: '8512'
  },
  {
    id: '8513',
    title: '2026 Raytree RMBD72ST 72" Drum Mulcher',
    category: 'Full-Size Skid Steer Attachments',
    type: 'Drum Mulcher',
    price: 8125,
    status: 'Available',
    image: 'assets/images/inventory/raytree-rmbd72st.jpg',
    serial: 'DRM202606202769',
    details: ['Brand new / unused', '72 inch drum mulcher', 'Skid steer attachment', 'Delivery available'],
    lot: '8513'
  },
  {
    id: '8529',
    title: '2026 Raytree RMBD50 50" Drum Mulcher',
    category: 'Full-Size Skid Steer Attachments',
    type: 'Drum Mulcher',
    price: 7065,
    status: 'Available',
    image: 'assets/images/inventory/raytree-rmbd50.jpg',
    serial: 'LM202606201931',
    details: ['Brand new / unused', '50 inch cutting width', 'Standard / low-flow style mulcher', 'Skid steer attachment', 'Delivery available'],
    lot: '8529'
  },
  {
    id: '8530',
    title: '2026 Raytree RMBD50 50" Drum Mulcher',
    category: 'Full-Size Skid Steer Attachments',
    type: 'Drum Mulcher',
    price: 7065,
    status: 'Available',
    image: 'assets/images/inventory/raytree-rmbd50.jpg',
    serial: 'LM202606201930',
    details: ['Brand new / unused', '50 inch cutting width', 'Skid steer attachment', 'Delivery available'],
    lot: '8530'
  },
  {
    id: '8533',
    title: '2026 Raytree REDM32 Mini Excavator Drum Mulcher',
    category: 'Mini Excavator Attachments',
    type: 'Excavator Mulcher',
    price: 5315,
    status: 'Available',
    image: 'assets/images/inventory/raytree-redm32.jpg',
    serial: 'EBD202606231501',
    details: ['Brand new / unused', '32 inch effective cutting width', 'For mini excavators', 'Delivery available'],
    lot: '8533'
  },
  {
    id: '8534',
    title: '2026 Raytree REDM32 Mini Excavator Drum Mulcher',
    category: 'Mini Excavator Attachments',
    type: 'Excavator Mulcher',
    price: 5315,
    status: 'Available',
    image: 'assets/images/inventory/raytree-redm32.jpg',
    serial: 'EBD202606201478',
    details: ['Brand new / unused', '32 inch effective cutting width', 'For mini excavators', 'Delivery available'],
    lot: '8534'
  },
  {
    id: '8535',
    title: '2026 Raytree REDM32 Mini Excavator Drum Mulcher',
    category: 'Mini Excavator Attachments',
    type: 'Excavator Mulcher',
    price: 5315,
    status: 'Available',
    image: 'assets/images/inventory/raytree-redm32.jpg',
    serial: 'EBD202606201477',
    details: ['Brand new / unused', '32 inch effective cutting width', 'For mini excavators', 'Delivery available'],
    lot: '8535'
  },
  {
    id: '8540',
    title: '2026 Raytree RMSC78 78" Hydraulic Power Rake',
    category: 'Full-Size Skid Steer Attachments',
    type: 'Power Rake',
    price: 3690,
    status: 'Available',
    image: 'assets/images/inventory/raytree-rmsc78.jpg',
    serial: 'SC202606201998',
    details: ['Brand new / unused', '78 inch power rake / soil conditioner', 'Control included', 'Skid steer attachment', 'Delivery available'],
    lot: '8540'
  },
  {
    id: '8541',
    title: '2026 Raytree RMH860 Hydraulic Hammer',
    category: 'Excavator Attachments',
    type: 'Hydraulic Hammer',
    price: 2495,
    status: 'Available',
    image: 'assets/images/inventory/raytree-rmh860.jpg',
    serial: 'HH20260620882',
    details: ['Brand new / unused', 'Hydraulic breaker / hammer', 'Call us to confirm machine fitment', 'Delivery available'],
    lot: '8541'
  },
  {
    id: '8251',
    title: 'Wolverine 60" Hydraulic Drum Mulcher',
    category: 'Full-Size Skid Steer Attachments',
    type: 'Drum Mulcher',
    price: 7000,
    status: 'Available',
    image: 'assets/images/inventory/wolverine-60.jpg',
    serial: 'ZW-00077',
    details: ['Brand new / unused', '60 inch working width', 'Skid steer attachment', 'Delivery available'],
    lot: '8251'
  },
  {
    id: '8349',
    title: 'Wolverine 60" Hydraulic Drum Mulcher',
    category: 'Full-Size Skid Steer Attachments',
    type: 'Drum Mulcher',
    price: 7000,
    status: 'Available',
    image: 'assets/images/inventory/wolverine-60.jpg',
    serial: 'ZW-00019',
    details: ['Brand new / unused', '60 inch working width', 'Skid steer attachment', 'Delivery available'],
    lot: '8349'
  },
  {
    id: '8363',
    title: 'Wolverine 60" Drum Mulcher',
    category: 'Full-Size Skid Steer Attachments',
    type: 'Drum Mulcher',
    price: 7000,
    status: 'Available',
    image: 'assets/images/inventory/wolverine-60.jpg',
    serial: 'ZW-00061',
    details: ['Brand new / unused', '60 inch working width', 'Skid steer attachment', 'Delivery available'],
    lot: '8363'
  },
  {
    id: '8220',
    title: 'Wolverine Mini Skid Steer Stump Grapple',
    category: 'Mini Skid Steer Attachments',
    type: 'Stump Grapple',
    price: 1495,
    status: 'Available',
    image: 'assets/images/inventory/mini-stump-grapple.jpg',
    serial: 'ZW-00646',
    details: ['Brand new / unused', 'Mini skid steer attachment', 'Stump / root grapple', 'Delivery available'],
    lot: '8220'
  },
  {
    id: '8422',
    title: 'Wolverine Mini Skid Steer Stump Grapple',
    category: 'Mini Skid Steer Attachments',
    type: 'Stump Grapple',
    price: 1495,
    status: 'Available',
    image: 'assets/images/inventory/mini-stump-grapple.jpg',
    serial: 'ZW-00778',
    details: ['Brand new / unused', 'Mini skid steer attachment', 'Stump / root grapple', 'Delivery available'],
    lot: '8422'
  },
  {
    id: '8257',
    title: '9-Piece Mini Excavator Attachment Set',
    category: 'Mini Excavator Attachments',
    type: 'Attachment Set',
    price: 1875,
    status: 'Available',
    image: 'assets/images/inventory/mini-excavator-9pc.jpg',
    serial: '',
    details: ['Brand new / unused', '9-piece attachment package', 'For mini excavators', 'Call to confirm pin size / fitment', 'Delivery available'],
    lot: '8257'
  },
  {
    id: '8258',
    title: '9-Piece Mini Excavator Attachment Set',
    category: 'Mini Excavator Attachments',
    type: 'Attachment Set',
    price: 1875,
    status: 'Available',
    image: 'assets/images/inventory/mini-excavator-9pc.jpg',
    serial: '',
    details: ['Brand new / unused', '9-piece attachment package', 'For mini excavators', 'Call to confirm pin size / fitment', 'Delivery available'],
    lot: '8258'
  },
  {
    id: '8154',
    title: 'Excavator Auger B-303TZLXZ-94',
    category: 'Excavator Attachments',
    type: 'Auger',
    price: 1695,
    status: 'Available',
    image: 'assets/images/inventory/excavator-auger.jpg',
    serial: '',
    details: ['Brand new / unused', 'Hydraulic excavator auger', 'Call to confirm machine fitment', 'Delivery available'],
    lot: '8154'
  },
  {
    id: '8156',
    title: 'G1Y1 TE31 5th Wheel Hydraulic Tow Hitch',
    category: 'Towing & Recovery',
    type: '5th Wheel Tow Hitch',
    price: 7500,
    status: 'Available',
    image: 'assets/images/inventory/tow-hitch.jpg',
    serial: 'KCTC2605105',
    details: ['Brand new / unused', 'Hydraulic fifth wheel tow hitch', 'Heavy-duty towing / recovery attachment', 'Delivery available'],
    lot: '8156'
  },
  {
    id: '8165',
    title: 'G1Y1 TE31 5th Wheel Hydraulic Tow Hitch',
    category: 'Towing & Recovery',
    type: '5th Wheel Tow Hitch',
    price: 7500,
    status: 'Available',
    image: 'assets/images/inventory/tow-hitch.jpg',
    serial: 'KCTC2605108',
    details: ['Brand new / unused', 'Hydraulic fifth wheel tow hitch', 'Heavy-duty towing / recovery attachment', 'Delivery available'],
    lot: '8165'
  },
  {
    id: '7993',
    title: 'SKLP Hydraulic Track Pin Press Machine',
    category: 'Shop Equipment',
    type: 'Pin Press',
    price: 1875,
    status: 'Available',
    image: 'assets/images/inventory/track-pin-press.jpg',
    serial: '',
    details: ['Hydraulic track pin press', 'Shop / repair equipment', 'Call for specifications', 'Delivery available'],
    lot: '7993'
  },
  {
    id: '7829',
    title: 'JCT Sand Blaster',
    category: 'Shop Equipment',
    type: 'Sand Blaster',
    price: 3000,
    status: 'Available',
    image: 'assets/images/inventory/sand-blaster.jpg',
    serial: '',
    details: ['JCT sand blasting machine', 'Shop equipment', 'Call for specifications', 'Delivery available'],
    lot: '7829'
  },
  {
    id: '7828',
    title: 'JCT Sand Blaster',
    category: 'Shop Equipment',
    type: 'Sand Blaster',
    price: 3000,
    status: 'Available',
    image: 'assets/images/inventory/sand-blaster.jpg',
    serial: '',
    details: ['JCT sand blasting machine', 'Shop equipment', 'Call for specifications', 'Delivery available'],
    lot: '7828'
  },
  {
    id: '8383',
    title: 'Wolverine 16-6T Mount Plate',
    category: 'Excavator Attachments',
    type: 'Mount Plate',
    price: 495,
    status: 'Available',
    image: 'assets/images/inventory/mount-plate.jpg',
    serial: 'ZW-10591',
    details: ['Mounting plate', 'Call us to confirm fitment', 'Delivery available'],
    lot: '8383'
  },
  {
    id: '7902',
    title: 'Landhero Water Pump',
    category: 'Other Equipment',
    type: 'Water Pump',
    price: 595,
    status: 'Available',
    image: 'assets/images/inventory/water-pump.jpg',
    serial: '',
    details: ['Portable water pump', 'Call for engine / pump specifications', 'Delivery available'],
    lot: '7902'
  }
];
